AppBundle\Entity\BookExemplar:
  type: entity
  id:
    id:
      type: string
      id: true
      generator:
        strategy: UUID
  fields:
    createdAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update
  manyToMany:
    pastLoans:
      targetEntity: AppBundle\Entity\BookLoan
      mappedBy: bookExemplar
      joinTable:
        name: book_exemplar_past_loans
        joinColumns:
          exemplar_id:
            referencedColumnName: id
        inverseJoinColumns:
          loan_id:
            referencedColumnName: id
  oneToOne:
    currentLoan:
      targetEntity: AppBundle\Entity\BookLoan
      mappedBy: bookExemplar
  manyToOne:
    book:
      targetEntity: AppBundle\Entity\Book
      mappedBy: book
      inversedBy: bookExemplars
    location:
      targetEntity: AppBundle\Entity\Location
      mappedBy: bookExemplars