AppBundle\Entity\Book:
  type: entity
  id:
    id:
      type: string
      id: true
      generator:
        strategy: UUID
  fields:
    title:
      type: string
    description:
      type: text
    isbn:
      type: string
    createdAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update
  manyToMany:
    genres:
      targetEntity: AppBundle\Entity\Genre
      inversedBy: belongsToBooks
  manyToOne:
    author:
      targetEntity: AppBundle\Entity\Author
      mappedBy: books
      inversedBy: books
  oneToMany:
    bookExemplars:
      targetEntity: AppBundle\Entity\BookExemplar
      mappedBy: book
      cascade: [PERSIST, REMOVE]
