AppBundle\Entity\BookLoan:
  type: entity
  id:
    id:
      type: string
      id: true
      generator:
        strategy: UUID
  fields:
    startDate:
      type: datetime
    dueDate:
      type: datetime
    pastDueFine:
      type: decimal
    createdAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: create
    updatedAt:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update
  manyToOne:
    bookExemplar:
      targetEntity: AppBundle\Entity\BookExemplar
      mappedBy: book
      inversedBy: loans
    member:
      targetEntity: AppBundle\Entity\Member
      mappedBy: member
      inversedBy: bookLoans
