home:
  prefix: /
  resource: routing/home.yml

book:
  prefix: /book
  resource: routing/book.yml

author:
  prefix: /author
  resource: routing/author.yml

dashboard:
  prefix: /dashboard
  resource: routing/dashboard.yml

genre:
  prefix: /genre
  resource: routing/genre.yml

security:
  prefix: /security
  resource: routing/security.yml

bookExemplar:
  prefix: /bookExemplar
  resource: routing/bookExemplar.yml

location:
  prefix: /location
  resource: routing/location.yml

employee:
  prefix: /employee
  resource: routing/employee.yml

member:
  prefix: /member
  resource: routing/member.yml

bookLoan:
  prefix: /bookLoan
  resource: routing/bookLoan.yml