home:
  prefix: /
  resource: routing/home.yml

book:
  prefix: /book
  resource: routing/book.yml

author:
  prefix: /author
  resource: routing/author.yml

dashboard:
  prefix: /dashboard
  resource: routing/dashboard.yml

genre:
  prefix: /genre
  resource: routing/genre.yml