version: '3'

services:
  webserver:
    volumes:
      - ./webserver/sites-enabled:/etc/nginx/sites-enabled
      - ../src:/srv/html
      - ../logs/nginx:/var/log/nginx
  database:
    ports:
      - "3306:3306"
  php:
    volumes:
      - ../src:/srv/html
  code:
    command: "pwd"