version: '3'

networks:
  app: ~
  sessions: ~
  data: ~

volumes:
  app: ~
  database: ~
  logs: ~

services:
  code:
    build:
      context: code
    volumes:
      - app:/srv/html/src
  php:
    build:
      context: php
    volumes:
      - app:/srv/html
    working_dir: /srv/html
    networks:
      - app
      - sessions
      - data
    restart: always
    expose:
      - 9000
    environment:
      - DATABASE_DATABASE=library_application
      - DATABASE_USER=library_system
      - DATABASE_PASSWORD=0c680e1cbdca42
      - DATABASE_HOST=database
  webserver:
    build:
      context: webserver
    volumes:
      - app:/srv/html
      - ./webserver/sites-enabled/example.com.conf:/etc/nginx/sites-enabled/example.com.conf
    working_dir: /srv/html
    restart: always
    ports:
      - "80:8080"
      - "433:8081"
    networks:
      - app
  sessions:
    image: redis:5.0.3
    networks:
      - sessions
    restart: always
    volumes:
      - logs:/var/log/redis
  database:
    image: mysql:5.7
    networks:
      - data
    volumes:
      - database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=library_application
      - MYSQL_USER=library_system
      - MYSQL_PASSWORD=0c680e1cbdca42
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    restart: always