app_bookExemplar_index:
  path: /
  defaults:
    _controller: AppBundle:BookExemplar:index

app_bookExemplar_create:
  path: /new
  defaults:
    _controller: AppBundle:BookExemplar:create

app_bookExemplar_view:
  path: /{bookExemplar}
  defaults:
    _controller: AppBundle:BookExemplar:view

app_bookExemplar_update:
  path: /{bookExemplar}/update
  defaults:
    _controller: AppBundle:BookExemplar:update

app_bookExemplar_delete:
  path: /{bookExemplar}/delete
  defaults:
    _controller: AppBundle:BookExemplar:delete