# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        database_provider:
            entity:
                class: AppBundle:Employee
                property: username

    role_hierarchy:
        ROLE_USER: []

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            #stateless: true

            form_login:
                login_path: 'app_security_login'
                check_path: 'app_security_login'
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /dashboard

    access_control:
        - { path: ^\/security/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^\/security/logout, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^\/.*, roles: ROLE_USER }
        - { path: ^\/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    encoders:
        AppBundle\Entity\Employee:
            algorithm: bcrypt
            cost: 12